apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: legacyapp.hirarinslab.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: hirarinslab.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: legacyapp
    # singular name to be used as an alias on the CLI and for display
    singular: legacyapp
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: LegacyApp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - la
  additionalPrinterColumns:
    - name: DB Host
      type: string
      description: Database Hostname
      JSONPath: .spec.db-hostname
    - name: DB Port
      type: integer
      description: Databse Port
      JSONPath: .spec.db-port
    - name: DB Scheme
      type: string
      description: Database Scheme
      JSONPath: .spec.db-scheme
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["db-hostname","db-port","db-scheme","db-user","db-password"]
          properties:
            db-hostname:
              type: string              
            db-port:
              type: integer
            db-dbname:
              type: string
            db-user:
              type: string
            db-password:
              type: string