apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: operator-container
          image: foobar3173/operator:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080