apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-timer
  labels:
    app: batch-timer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-timer
  template:
    metadata:
      labels:
        app: batch-timer
    spec:
      containers:
      # Legacy Batch Timer
      - name: batch-timer
        image: satoshi55d/regacy-app:1.0.0
        imagePullPolicy: Always
        command: ["/start-batch-timer.sh"]
      # BatchTimerのRMI通信をProxyしてBatchServerへ転送するアンバサダーコンテナを差し込み。  
      - name: tcp-proxy
        image: satoshi55d/haproxy:1.0.0
        imagePullPolicy: Always
        env:
        - name: BATCH_SERVER_ADDRESS
          value: "batch-server.default.svc.cluster.local"
      # バッチ処理リカバリ用コンテナを差し込み
      - name: batch-recovery
        image: satoshi55d/batch-recovery:1.0.0
        imagePullPolicy: Always

      restartPolicy: Always
